
# View
set -g status-interval 5
set -g status-left-length 16
set -g status-right-length 50

set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=cyan,bold][#14H:#S]#[default]]'
set -g status-right '|#[fg=magenta,bold]#(load.sh)#[default]| #[fg=blue,bold][%a %m/%d %H:%M]#[default]'

# Option
setw -g mode-keys vi

## Bindings
# remap prefix key
unbind-key C-b
set -g prefix C-b
set -g mouse on
set -g set-clipboard on

# key binds
bind-key r source-file ~/.tmux.conf; display-message "Reloading configurations.."

bind-key : command-prompt
unbind-key s
bind-key s split-window -v
bind-key v split-window -h

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key < resize-pane -L 5
bind-key > resize-pane -R 5
bind-key - resize-pane -D 5
bind-key + resize-pane -U 5

#bind-key k kill-pane
#bind-key K kill-window
bind-key i display-panes
bind-key y copy-mode
bind-key p paste-buffer

bind-key a set-window-option synchronize-panes on
bind-key A set-window-option synchronize-panes off

# copy mode
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
